spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    defer-datasource-initialization: true
    #전송 쿼리 확인
    show-sql: true
    hibernate :
      ddl-auto : update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url : jdbc:h2:mem:test
    username: sa

  h2:
    console:
      enabled: true
    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

jwt:
  issuer: oslsl123o@gmail.com
  secret_key : study_springboot